token: "0404aebfdffa0dfe135cf2734763c453f6b1f16ee6a1292d22efde29029b743eb82ddf19e4566600b802a"
db_url: "postgres://ekwnrdcxfuqexb:a14bcd9cbb50869157293d4530d225271b1f48462903972d085028fa63bef806@ec2-3-214-46-194.compute-1.amazonaws.com:5432/d9rc9g12b2lbbu"

message_sign_up: "ะขั ะทะฐะฟะธัะฐะฝ ะฝะฐ ััะตะฝะธัะพะฒะบั "
message_sign_out: "ะขั ะพัะฟะธัะฐะปัั ะพั ััะตะฝะธัะพะฒะบะธ"
message_default: "ะัััะต ะฟะพะพะฑัะฐะตะผัั ะฝะฐ ััะตะฝะธัะพะฒะบะต!"
message_non_train: "ะฃ ัะตะฑั ะตัะต ะฝะตั ะฝะธ ะพะดะฝะพะน ััะตะฝะธัะพะฒะบะธ. ะััััะตะน ะทะฐะฟะธััะฒะฐะนัั!"

count_train: 6
main_keyboard:
  - label: "๐๐ปโโ๏ธ ะะพะฝะณัะฐะฝ ะะ 19:00"
    coach: "\nะขัะตะฝะตั: ะกะตัะณะตะน ะะฐะฒะปะพะฒ\n\nะ ะะ ะฟัะพัะพะดัั ะตัะต ะดะฒะต ััะตะฝะธัะพะฒะบะธ ัะพะฒะผะตััะฝะพ ั ะฑะตะณะพะฒัะผ ะบะปัะฑะพะผ PUMA @rrunderground. ะะพั ะพะฝะธ:\n\n๐๐ปโโ ะะพะฝะณัะฐะฝ 12 ะบะผ, ัะตะผะฟ 6 ะผะธะฝ/ะบะผ\nะะ 19:00\nะผ. ะคััะฝะทะตะฝัะบะฐั\n\n๐๐ปโโ ะะพะฝะณัะฐะฝ 12 ะบะผ, ัะตะผะฟ 5 ะผะธะฝ/ะบะผ\nะะ 19:00\nะผ. ะคััะฝะทะตะฝัะบะฐั"
  - label: "๐ ะะฑัะฐั ะะข 19:30"
    coach: "\nะขัะตะฝะตั: ะัััะผ ะัะปะพะฒ\n\n"
  - label: "๐๐ปโโ๏ธ ะะพะฝะณัะฐะฝ ะกะ 19:00"
    coach: "\nะขัะตะฝะตั: ะกะตัะณะตะน ะะฐะฒะปะพะฒ\n\n"
  - label: "๐ ะะฑัะฐั ะงะข 19:30"
    coach: "\nะขัะตะฝะตั: ะัััะผ ะัะปะพะฒ\n\n"
  - label: "๐๐ปโโ๏ธ ะะพะฝะณัะฐะฝ ะะข 19:00"
    coach: "\nะขัะตะฝะตั: ะกะตัะณะตะน ะะฐะฒะปะพะฒ\n\n"
  - label: "๐๐ปโโ๏ธ ะะพะฝะณัะฐะฝ ะะก 9:00(9:20)"
    coach: "\nะขัะตะฝะตั: ะกััะฐะนะปะธ ะฅะพัะฐะผะพะฒ\n\n"
schedule: "๐ ะะฐัะฟะธัะฐะฝะธะต"
sch_photo: "photo-186543814_457239215"
my_train: "๐คธโโ๏ธ ะะพะธ ััะตะฝะธัะพะฒะบะธ"
